package com.mooclient.util;

public class MooLanguage {

    public static final String PL = "pl";
    public static final String EN = "en";

    public static String current = PL;

    public static String get(String key) {
        if (key == null) return "";

        if (PL.equals(current)) {
            return switch (key) {
                case "back" -> "Wstecz";
                case "settings" -> "Ustawienia";
                case "singleplayer" -> "Tryb Jednoosobowy";
                case "multiplayer" -> "Tryb Wieloosobowy";
                case "quit" -> "Wyjdź z gry";
                case "options" -> "OPCJE";
                case "enabled" -> "WŁĄCZONE";
                case "disabled" -> "WYŁĄCZONE";
                case "esc_hint" -> "Wciśnij ESC lub PRAWY SHIFT, aby zamknąć";
                case "mods_title" -> "MOO CLIENT • MODY";
                case "mods_button", "mods" -> "MODY";
                case "gamma_desc" -> "Maksymalna jasność w ciemnych jaskiniach";
                case "fps_desc" -> "Licznik FPS na ekranie";
                case "sprint_desc" -> "Automatyczny Toggle Sprint";
                case "freelook_desc" -> "Widok kamery 360° bez obracania postaci";
                case "potions_desc" -> "Aktywne efekty mikstur i odliczanie";
                case "nametags_desc" -> "Własny styl nicków graczy i ping";
                case "zoom_desc" -> "Płynne przybliżenie kamery (Zoom)";
                case "chat_desc" -> "Przezroczysty czat i historia";
                case "ping_desc" -> "Licznik pingu na ekranie";
                case "macro_desc" -> "Własne bindy komend i wiadomości";
                case "waypoints_desc" -> "Punkty nawigacyjne i promień w świecie";
                case "cps_desc" -> "Licznik kliknięć na sekundę (CPS)";
                case "armor_name" -> "Armor HUD";
                case "armor_desc" -> "Wyświetla założony set zbroi i stan wytrzymałości";
                case "armor_opt_title" -> "ARMOR HUD";
                case "armor_opt_subtitle" -> "Wyświetlanie założonej zbroi, paska wytrzymałości i pozycji na ekranie.";
                case "emotes_name" -> "Emotki";
                case "emotes_desc" -> "Animacje postaci (Salta, Gesty, Interakcje)";
                case "emotes_opt_title" -> "EMOTKI";
                case "emotes_opt_subtitle" -> "Wybór emotek z koła, gesty i animacje postaci.";
                case "emotes_hands_up_label" -> "Klawisz rąk w górę";
                case "emotes_frontflip_label" -> "Klawisz salta w przód";
                case "emotes_backflip_label" -> "Klawisz salta w tył";
                case "emotes_wheel_key_label" -> "Koło wyboru emotek (Wheel)";
                case "interaction_accept_key_label" -> "Akceptacja zaproszenia";
                case "interaction_decline_key_label" -> "Odrzucenie zaproszenia";
                case "emotes_restore_perspective_label" -> "Powrót do 1st person po zakończeniu";
                case "emotes_wheel_title" -> "WYBIERZ EMOTKĘ";

                // Aktywne Emotki Solo i Multiplayer
                case "emotes_wheel_frontflip", "emote.mooclient.frontflip", "frontflip" -> "Salto w przód";
                case "emotes_wheel_backflip", "emote.mooclient.backflip", "backflip" -> "Salto w tył";
                case "emotes_wheel_hands_up", "emote.mooclient.hands_up", "hands_up" -> "Ręce w górę";
                case "emotes_wheel_meditation", "emote.mooclient.meditation", "meditation" -> "Medytacja";
                case "emotes_wheel_friendly_wave", "emote.mooclient.friendly_wave", "friendly_wave" -> "Przyjazne machanie";
                case "emotes_wheel_facepalm", "emote.mooclient.facepalm", "facepalm" -> "Facepalm";
                case "emotes_wheel_handshake", "emote.mooclient.handshake", "handshake" -> "Uścisk dłoni";
                case "emotes_wheel_stop" -> "Zatrzymaj";

                // UI & Editor
                case "emotes_wheel_hint" -> "Wskaż emotkę myszą i puść klawisz lub kliknij";
                case "emotes_edit_wheel_btn" -> "⚙ Edytuj koło";
                case "emotes_editor_title" -> "KONFIGURATOR KOŁA EMOTEK";
                case "emotes_editor_subtitle" -> "Przeciągaj emotki na koło, zamieniaj kolejność lub usuwaj przeciągając do kosza.";
                case "emotes_dock_title" -> "Biblioteka emotek (Chwyć i przeciągnij na koło):";
                case "emotes_trash_zone" -> "🗑 Przeciągnij tutaj, aby usunąć";
                case "emotes_trash_title" -> "🗑 USUŃ Z KOŁA";
                case "emotes_trash_subtitle" -> "Przeciągnij tutaj";
                case "emotes_drop_in_slot" -> "+ UPUŚĆ W SLOCIE #";
                case "emotes_all_assigned" -> "✓ Wszystkie dostępne emotki są już przypisane do koła!";
                case "emotes_unlocked" -> "§aOdblokowane";
                case "emotes_rank_required" -> "§cWymaga rangi";
                case "emotes_slot_prefix" -> "Slot #";
                case "emotes_save_btn" -> "✔ Zapisz i zamknij";
                case "emotes_reset_btn" -> "↺ Domyślne";
                case "emotes_wheel_empty" -> "> KOŁO JEST PUSTE (KLIKNIJ EDYTUJ KOŁO) <";
                case "emotes_locked" -> "[SKLEP]";
                case "emotes_store_required" -> "Wymaga zakupu w sklepie Moo Client";
                case "emotes_dev_badge" -> "DEV MOO CLIENT";
                case "emotes_tester_badge" -> "TESTER";

                // Interaction Engine & Invitations
                case "invitation_title" -> "ZAPROSZENIE DO INTERAKCJI";
                case "invitation_accept_prompt", "invitation_accept" -> "Akceptuj";
                case "invitation_decline_prompt", "invitation_decline" -> "Odrzuć";
                case "invitation_desc" -> "zaprasza do";
                case "invitation_header" -> "INTERAKCJA MOO CLIENT";
                case "invitation_offers" -> "oferuje";
                case "interaction_requires_multiplayer" -> "Interakcje multiplayer wymagają gry wieloosobowej i innego gracza!";
                case "interaction_no_target_found", "interaction_no_target" -> "Nie znaleziono gracza w zasięgu wzroku (< 3.0 bloków)!";
                case "interaction_in_progress", "interaction_already_active" -> "Trwa już inna interakcja!";
                case "interaction_cancelled" -> "Interakcja została anulowana.";
                case "interaction_declined" -> "Gracz {target} odrzucił zaproszenie do interakcji.";
                case "interaction_interrupted" -> "Interakcja przerwana przez ruch lub obrażenia!";
                case "interaction_expired" -> "Zaproszenie do interakcji wygasło.";
                case "interaction_cooldown", "interaction_rate_limited" -> "Poczekaj chwilę przed wysłaniem kolejnego zaproszenia!";
                case "interaction_not_moo_user" -> "nie używa klienta Moo Client.";
                case "interaction_no_permission" -> "Brak uprawnień do tej emotki multiplayer.";
                case "interaction_sent", "interaction_invited" -> "Wysłano zaproszenie do interakcji {emote} dla gracza {target}.";

                // General UI & Keybinds
                case "keybind_label" -> "Klawisz aktywacji";
                case "press_key_hint" -> "> WCIŚNIJ KLAWISZ <";
                case "mode_hold" -> "Przytrzymaj";
                case "mode_toggle" -> "Przełącznik";
                case "cps_opt_title" -> "CPS";
                case "cps_opt_subtitle" -> "Wyświetlaj i dostosuj licznik CPS na ekranie.";
                case "cps_buttons_label" -> "Wyświetlane przyciski";
                case "fps_prefix_label" -> "Prefiks 'FPS:'";
                case "ping_prefix_label" -> "Prefiks 'Ping:'";
                case "cps_prefix_label" -> "Nazwa 'CPS'";
                case "scoreboard_desc" -> "Dostosowanie pozycji, cienia i tła tabeli wyników";
                case "scoreboard_opt_title" -> "SCOREBOARD";
                case "scoreboard_opt_subtitle" -> "Dostosuj pozycję, cień tekstu, tło i numery.";
                case "scoreboard_scores_label" -> "Pokaż punkty / liczby";
                case "fps_opt_title" -> "FPS";
                case "fps_opt_subtitle" -> "Wyświetlaj i dostosuj FPS na ekranie.";
                case "ping_opt_title" -> "PING";
                case "ping_opt_subtitle" -> "Wyświetlaj i dostosuj opóźnienie (ping) na ekranie.";
                case "waypoints_opt_title" -> "WAYPOINTS";
                case "waypoints_opt_subtitle" -> "Punkty w świecie gry, odległości i promienie.";
                case "waypoints_open_gui" -> "📍 Otwórz Menedżer Waypointów";
                case "show_distance_label" -> "Pokaż dystans (metry)";
                case "show_beacons_label" -> "Promienie do nieba";
                case "show_labels_label" -> "Etykiety nazw w świecie";
                case "sprint_opt_title" -> "SPRINT";
                case "sprint_opt_subtitle" -> "Dostosuj wskaźnik Toggle Sprint.";
                case "freelook_opt_title" -> "FREELOOK";
                case "freelook_opt_subtitle" -> "Obracanie kamery 360° bez ruchu postaci.";
                case "potions_opt_title" -> "EFEKTY MIKSTUR";
                case "potions_opt_subtitle" -> "Wyświetlaj aktywne mikstury i liczniki czasu.";
                case "nametags_opt_title" -> "NAMETAGS";
                case "nametags_opt_subtitle" -> "Dostosuj plakietki graczy i kolorowy ping.";
                case "zoom_opt_title" -> "ZOOM";
                case "zoom_opt_subtitle" -> "Dostosuj klawisz i mnożnik przybliżenia.";
                case "macro_opt_title" -> "MAKRA / AUTOTEXT";
                case "macro_opt_subtitle" -> "Wysyłaj komendy i wiadomości klawiszami.";
                case "macro_enabled_label" -> "Włącz moduł";
                case "macro_add_btn" -> "Dodaj nowe makro (%d/10)";
                case "macro_max_reached" -> "Maksymalna liczba 10 makr osiągnięta";
                case "chat_opt_title" -> "CZAT";
                case "chat_opt_subtitle" -> "Przezroczyste tło, nieskończona historia, stackowanie i animacja";
                case "chat_transparent_label" -> "Przezroczyste tło";
                case "chat_unlimited_label" -> "Nieskończona historia";
                case "chat_stack_label" -> "Stackowanie wiadomości";
                case "chat_smooth_label" -> "Płynna animacja czatu";
                case "itemscale_opt_title" -> "ITEM SCALE";
                case "itemscale_opt_subtitle" -> "Powiększanie leżących itemów (Totemy, Koxy, Zbroje) podczas PvP";
                case "itemscale_enabled_label" -> "Włącz moduł";
                case "itemscale_profile_label" -> "Profil";
                case "itemscale_highlight_scale_label" -> "Skala wyróżnionych itemów";
                case "itemscale_default_scale_label" -> "Skala pozostałych itemów";
                case "itemscale_enchanted_label" -> "Powiększaj każdy enchantowany";
                case "itemscale_items_list_label" -> "Wyróżnione przedmioty";
                case "itemscale_search_placeholder" -> "Szukaj lub wpisz ID itemu...";
                case "style_label" -> "Styl wyglądu";
                case "bg_label" -> "Tło widżetu";
                case "shadow_label" -> "Cień tekstu";
                case "prefix_label" -> "Prefiks 'FPS:'";
                case "compact_label" -> "Tryb kompaktowy";
                case "show_ping_label" -> "Pokaż ping";
                case "show_self_ping_label" -> "Pokaż własny ping";
                case "ping_pos_label" -> "Pozycja pingu";
                case "ping_pos_beside" -> "Obok nicku";
                case "ping_pos_above" -> "Nad nickiem";
                case "show_logo_label" -> "Znaczek logo klienta";
                case "remove_bg_label" -> "Usuń tło nametagów";
                case "waypoint_scale_label" -> "Skala / Rozmiar waypointów";
                case "death_waypoint_label" -> "Automatyczny punkt po śmierci";
                case "wp_all_dimensions" -> "Wszystkie wymiary";
                case "wp_all_servers" -> "Wszystkie serwery";
                case "wp_custom_color" -> "Własny kolor";
                case "factor_label" -> "Mnożnik przybliżenia";
                case "smooth_zoom_label" -> "Płynny zoom";
                case "gamma_opt_title" -> "GAMMA";
                case "gamma_opt_subtitle" -> "Widoczność w ciemnych jaskiniach i w nocy";
                case "fullbright_label" -> "Wizja Fullbright";
                case "orientation_label" -> "Orientacja";
                case "horizontal_label" -> "Pozioma";
                case "vertical_label" -> "Pionowa";
                case "durability_text_label" -> "Tekst wytrzymałości (góra)";
                case "dur_none_label" -> "Brak";
                case "dur_percent_label" -> "Procenty (%)";
                case "dur_value_label" -> "Wartość";
                case "show_max_durability_label" -> "Pokaż maks. wytrzymałość (np. 250/528)";
                case "durability_bar_label" -> "Pasek wytrzymałości (dół)";
                case "durability_warning_label" -> "Dźwięk krówki (< 12.5% zbroi)";
                case "durability_critical_alert" -> "Uwaga! Wytrzymałość Twojej zbroi jest krytycznie niska!";
                case "show_empty_slots_label" -> "Puste sloty";
                case "shulker_desc" -> "Podgląd zawartości Shulker Boxów w ekwipunku";
                case "shulker_opt_title" -> "SHULKER TOOLTIP";
                case "shulker_opt_subtitle" -> "Podgląd zawartości Shulker Boxów bezpośrednio w okienku tooltip.";
                case "shulker_enabled_label" -> "Włącz moduł";
                case "shulker_inspect_label" -> "Inspekcja przedmiotów (SHIFT)";
                case "shulker_color_border_label" -> "Kolor ramki wg shulkera";
                case "shulker_empty_slots_label" -> "Wyświetlaj puste sloty";
                case "shulker_require_shift_label" -> "Wymagaj SHIFT do otwarcia";
                case "invview_desc" -> "Podgląd 3 rzędów głównego ekwipunku na ekranie";
                case "invview_opt_title" -> "INVENTORY VIEW";
                case "invview_opt_subtitle" -> "Podgląd 3 rzędów ekwipunku na ekranie pod klawiszem [I].";
                case "invview_enabled_label" -> "Włącz moduł";
                case "invview_keybind_label" -> "Klawisz aktywacji";
                case "show_offhand_label" -> "Druga ręka (Offhand)";
                case "show_mainhand_label" -> "Główna ręka";
                case "mode_label" -> "Tryb aktywacji";
                case "invert_pitch_label" -> "Odwróć oś Y";
                case "client_settings_title" -> "MOO CLIENT • USTAWIENIA";
                case "tab_accent" -> "🎨 KOLOR AKCENTU";
                case "tab_hud" -> "📍 HUD I WIDŻETY";
                case "tab_gui" -> "✨ MOTYW GUI";
                case "tab_emotes" -> "🕺 EMOTKI";
                case "tab_profiles" -> "📁 PROFILE";
                case "reset_hud_btn" -> "↺ ZRESETUJ POZYCJE HUD";
                case "reset_hud_done" -> "✓ Zresetowano pozycje HUD!";
                case "hud_snapping_label" -> "Przyciąganie do krawędzi (Snapping)";
                case "hud_scale_label" -> "Skala widżetów HUD";
                case "global_shadow_label" -> "Globalny cień tekstu HUD";
                case "bg_dim_label" -> "Przyciemnienie tła menu";
                case "gui_anim_label" -> "Płynne animacje najechania";
                case "custom_rgb_label" -> "Własny kolor (Suwaki RGB):";
                case "active_badge" -> "✓ AKTYWNY";
                case "activate_btn" -> "AKTYWUJ";
                case "accounts_title" -> "KONTA PREMIUM";
                case "add_account_btn" -> "+ Dodaj konto";
                case "active_account" -> "Aktywne";
                case "enter_nickname" -> "Wpisz nick...";
                case "login_microsoft" -> "🔑 Logowanie Microsoft";
                case "open_browser" -> "Otwórz link";
                case "cancel" -> "Anuluj";
                case "logged_in_as" -> "Zalogowano jako ";
                default -> key;
            };
        } else {
            return switch (key) {
                case "back" -> "Back";
                case "settings" -> "Settings";
                case "singleplayer" -> "Singleplayer";
                case "multiplayer" -> "Multiplayer";
                case "quit" -> "Quit Game";
                case "options" -> "OPTIONS";
                case "enabled" -> "ENABLED";
                case "disabled" -> "DISABLED";
                case "esc_hint" -> "Press ESC or RIGHT SHIFT to close";
                case "mods_title" -> "MOO CLIENT • MODS";
                case "mods_button", "mods" -> "MODS";
                case "gamma_desc" -> "Max brightness for dark caves";
                case "fps_desc" -> "FPS Counter on HUD";
                case "sprint_desc" -> "Automatic Toggle Sprint";
                case "freelook_desc" -> "360° Free Camera View";
                case "potions_desc" -> "Active Potions & Timers";
                case "nametags_desc" -> "Nametag Badges & Ping";
                case "zoom_desc" -> "Smooth Camera Zoom";
                case "chat_desc" -> "Transparent Chat & History";
                case "ping_desc" -> "Ping Latency on HUD";
                case "macro_desc" -> "Macro Command Keybinds";
                case "waypoints_desc" -> "In-world waypoints and beacon beams";
                case "cps_desc" -> "Clicks Per Second (CPS) on HUD";
                case "armor_name" -> "Armor HUD";
                case "armor_desc" -> "Displays equipped armor set and durability status";
                case "armor_opt_title" -> "ARMOR HUD";
                case "armor_opt_subtitle" -> "Customize equipped armor display, durability bar and screen position.";
                case "emotes_name" -> "Emotes";
                case "emotes_desc" -> "Player animations (Flips, Gestures, Interactions)";
                case "emotes_opt_title" -> "EMOTES";
                case "emotes_opt_subtitle" -> "Perform flips, dances, gestures and animations.";
                case "emotes_hands_up_label" -> "Hands Up Keybind";
                case "emotes_frontflip_label" -> "Frontflip Keybind";
                case "emotes_backflip_label" -> "Backflip Keybind";
                case "emotes_wheel_key_label" -> "Emote Wheel Keybind";
                case "interaction_accept_key_label" -> "Accept Invitation Key";
                case "interaction_decline_key_label" -> "Decline Invitation Key";
                case "emotes_restore_perspective_label" -> "Return to 1st Person on Finish";
                case "emotes_wheel_title" -> "SELECT EMOTE";

                // Active Solo & Multiplayer Emotes
                case "emotes_wheel_frontflip", "emote.mooclient.frontflip", "frontflip" -> "Frontflip";
                case "emotes_wheel_backflip", "emote.mooclient.backflip", "backflip" -> "Backflip";
                case "emotes_wheel_hands_up", "emote.mooclient.hands_up", "hands_up" -> "Hands Up";
                case "emotes_wheel_meditation", "emote.mooclient.meditation", "meditation" -> "Meditation";
                case "emotes_wheel_friendly_wave", "emote.mooclient.friendly_wave", "friendly_wave" -> "Friendly Wave";
                case "emotes_wheel_facepalm", "emote.mooclient.facepalm", "facepalm" -> "Facepalm";
                case "emotes_wheel_handshake", "emote.mooclient.handshake", "handshake" -> "Handshake";
                case "emotes_wheel_stop" -> "Stop";

                // UI & Editor
                case "emotes_wheel_hint" -> "Hover over emote and release key or click";
                case "emotes_edit_wheel_btn" -> "⚙ Edit Wheel";
                case "emotes_editor_title" -> "EMOTE WHEEL EDITOR";
                case "emotes_editor_subtitle" -> "Drag & drop emotes to wheel, reorder or drag to trash to remove.";
                case "emotes_dock_title" -> "Emote Library (Drag & drop onto wheel):";
                case "emotes_trash_zone" -> "🗑 Drag here to remove";
                case "emotes_trash_title" -> "🗑 REMOVE FROM WHEEL";
                case "emotes_trash_subtitle" -> "Drag here";
                case "emotes_drop_in_slot" -> "+ DROP IN SLOT #";
                case "emotes_all_assigned" -> "✓ All available emotes are already assigned to the wheel!";
                case "emotes_unlocked" -> "§aUnlocked";
                case "emotes_rank_required" -> "§cRank required";
                case "emotes_slot_prefix" -> "Slot #";
                case "emotes_save_btn" -> "✔ Save & Close";
                case "emotes_reset_btn" -> "↺ Reset";
                case "emotes_wheel_empty" -> "> WHEEL IS EMPTY (CLICK EDIT WHEEL) <";
                case "emotes_locked" -> "[STORE]";
                case "emotes_store_required" -> "Requires Moo Client Store Unlock";
                case "emotes_dev_badge" -> "DEV MOO CLIENT";
                case "emotes_tester_badge" -> "TESTER";

                // Interaction Engine & Invitations
                case "invitation_title" -> "INTERACTION INVITATION";
                case "invitation_accept_prompt", "invitation_accept" -> "Accept";
                case "invitation_decline_prompt", "invitation_decline" -> "Decline";
                case "invitation_desc" -> "invites you to";
                case "invitation_header" -> "MOO CLIENT INTERACTION";
                case "invitation_offers" -> "offers";
                case "interaction_requires_multiplayer" -> "Multiplayer interactions require multiplayer mode and another player!";
                case "interaction_no_target_found", "interaction_no_target" -> "No Moo Client player found in crosshair sight (< 3.0 blocks)!";
                case "interaction_in_progress", "interaction_already_active" -> "Another interaction is already in progress!";
                case "interaction_cancelled" -> "Interaction cancelled.";
                case "interaction_declined" -> "Player {target} declined the interaction.";
                case "interaction_interrupted" -> "Interaction interrupted by movement or damage!";
                case "interaction_expired" -> "Interaction invitation expired.";
                case "interaction_cooldown", "interaction_rate_limited" -> "Please wait a moment before sending another invitation!";
                case "interaction_not_moo_user" -> "is not using Moo Client.";
                case "interaction_no_permission" -> "No permission for this multiplayer emote.";
                case "interaction_sent", "interaction_invited" -> "Sent {emote} interaction invitation to {target}.";

                // General UI & Keybinds
                case "keybind_label" -> "Activation Keybind";
                case "press_key_hint" -> "> PRESS ANY KEY <";
                case "mode_hold" -> "Hold";
                case "mode_toggle" -> "Toggle";
                case "cps_opt_title" -> "CPS";
                case "cps_opt_subtitle" -> "Display and customize your CPS counter on the HUD.";
                case "cps_buttons_label" -> "Displayed Buttons";
                case "fps_prefix_label" -> "Show 'FPS:' Prefix";
                case "ping_prefix_label" -> "Show 'Ping:' Prefix";
                case "cps_prefix_label" -> "Show 'CPS' Name";
                case "scoreboard_desc" -> "Customize scoreboard position, background, shadows and scores";
                case "scoreboard_opt_title" -> "SCOREBOARD";
                case "scoreboard_opt_subtitle" -> "Reposition scoreboard, toggle text shadow, background and scores.";
                case "scoreboard_scores_label" -> "Show Scores / Numbers";
                case "fps_opt_title" -> "FPS";
                case "fps_opt_subtitle" -> "Display and customize your FPS on the HUD.";
                case "ping_opt_title" -> "PING";
                case "ping_opt_subtitle" -> "Display and customize your real-time latency on the HUD.";
                case "waypoints_opt_title" -> "WAYPOINTS";
                case "waypoints_opt_subtitle" -> "In-world navigation points, distances and beacon beams.";
                case "waypoints_open_gui" -> "📍 Open Waypoints Manager";
                case "show_distance_label" -> "Show Distance (Meters)";
                case "show_beacons_label" -> "Show Sky Beacon Beams";
                case "show_labels_label" -> "Show In-World Name Labels";
                case "sprint_opt_title" -> "SPRINT";
                case "sprint_opt_subtitle" -> "Customize your Toggle Sprint indicator on HUD.";
                case "freelook_opt_title" -> "FREELOOK";
                case "freelook_opt_subtitle" -> "Free 360° camera rotation without moving character.";
                case "potions_opt_title" -> "POTION EFFECTS";
                case "potions_opt_subtitle" -> "Display active potions and countdown timer on HUD.";
                case "nametags_opt_title" -> "NAMETAGS";
                case "nametags_opt_subtitle" -> "Customize player nametags and colored ping latency.";
                case "zoom_opt_title" -> "ZOOM";
                case "zoom_opt_subtitle" -> "Customize zoom keybind and magnification factor.";
                case "macro_opt_title" -> "MACRO / AUTOTEXT";
                case "macro_opt_subtitle" -> "Execute commands & messages using custom keybinds.";
                case "macro_enabled_label" -> "Enable Module";
                case "macro_add_btn" -> "Add New Macro (%d/10)";
                case "macro_max_reached" -> "Maximum 10 macros reached";
                case "chat_opt_title" -> "CHAT";
                case "chat_opt_subtitle" -> "Transparent background, unlimited history, message stacking & smooth animation";
                case "chat_transparent_label" -> "Transparent Background";
                case "chat_unlimited_label" -> "Unlimited Chat History";
                case "chat_stack_label" -> "Stack Messages";
                case "chat_smooth_label" -> "Smooth Chat Animation";
                case "itemscale_opt_title" -> "ITEM SCALE";
                case "itemscale_opt_subtitle" -> "Scale up dropped items (Totems, Gaps, Armor) in PvP";
                case "itemscale_enabled_label" -> "Enable Module";
                case "itemscale_profile_label" -> "Profile";
                case "itemscale_highlight_scale_label" -> "Highlighted Items Scale";
                case "itemscale_default_scale_label" -> "Other Items Scale";
                case "itemscale_enchanted_label" -> "Scale All Enchanted Items";
                case "itemscale_items_list_label" -> "Highlighted Items";
                case "itemscale_search_placeholder" -> "Search or enter item ID...";
                case "style_label" -> "Appearance Style";
                case "bg_label" -> "Show Background";
                case "shadow_label" -> "Text Shadow";
                case "prefix_label" -> "Show 'FPS:' Prefix";
                case "compact_label" -> "Compact Mode";
                case "show_ping_label" -> "Show Ping";
                case "show_self_ping_label" -> "Show Self Ping";
                case "ping_pos_label" -> "Ping Position";
                case "ping_pos_beside" -> "Beside Name";
                case "ping_pos_above" -> "Above Name";
                case "show_logo_label" -> "Client Logo Badge";
                case "remove_bg_label" -> "Remove Nametag Background";
                case "waypoint_scale_label" -> "Waypoint Scale / Size";
                case "death_waypoint_label" -> "Auto Death Waypoint";
                case "wp_all_dimensions" -> "All Dimensions";
                case "wp_all_servers" -> "All Servers";
                case "wp_custom_color" -> "Custom Color";
                case "factor_label" -> "Zoom Factor";
                case "smooth_zoom_label" -> "Smooth Zoom";
                case "gamma_opt_title" -> "GAMMA";
                case "gamma_opt_subtitle" -> "See clearly in dark caves and night";
                case "fullbright_label" -> "Fullbright Vision";
                case "orientation_label" -> "Orientation";
                case "horizontal_label" -> "Horizontal";
                case "vertical_label" -> "Vertical";
                case "durability_text_label" -> "Top Durability Text";
                case "dur_none_label" -> "None";
                case "dur_percent_label" -> "Percent (%)";
                case "dur_value_label" -> "Value";
                case "show_max_durability_label" -> "Show Max Durability (e.g. 250/528)";
                case "durability_bar_label" -> "Bottom Durability Bar";
                case "durability_warning_label" -> "Cow Sound Warning (< 12.5% dur)";
                case "durability_critical_alert" -> "Warning! Your armor durability is critically low!";
                case "show_empty_slots_label" -> "Show Empty Slots";
                case "shulker_desc" -> "Preview Shulker Box inventory in tooltips";
                case "shulker_opt_title" -> "SHULKER TOOLTIP";
                case "shulker_opt_subtitle" -> "Preview Shulker Box contents directly in item tooltips.";
                case "shulker_enabled_label" -> "Enable Module";
                case "shulker_inspect_label" -> "Item Inspection (SHIFT Lock)";
                case "shulker_color_border_label" -> "Color-Matched Border";
                case "shulker_empty_slots_label" -> "Show Empty Slots";
                case "shulker_require_shift_label" -> "Require SHIFT to Open";
                case "invview_desc" -> "Preview 3 rows of main inventory on HUD";
                case "invview_opt_title" -> "INVENTORY VIEW";
                case "invview_opt_subtitle" -> "Preview 3 rows of main inventory on HUD with keybind [I].";
                case "invview_enabled_label" -> "Enable Module";
                case "invview_keybind_label" -> "Activation Keybind";
                case "show_offhand_label" -> "Show Offhand";
                case "show_mainhand_label" -> "Show Main Hand";
                case "mode_label" -> "Activation Mode";
                case "invert_pitch_label" -> "Invert Y-Axis";
                case "client_settings_title" -> "MOO CLIENT • SETTINGS";
                case "tab_accent" -> "🎨 ACCENT COLOR";
                case "tab_hud" -> "📍 HUD & WIDGETS";
                case "tab_gui" -> "✨ GUI THEME";
                case "tab_emotes" -> "🕺 EMOTES";
                case "tab_profiles" -> "📁 PROFILES";
                case "reset_hud_btn" -> "↺ RESET HUD POSITIONS";
                case "reset_hud_done" -> "✓ HUD Positions Reset!";
                case "hud_snapping_label" -> "Edge Snapping (HUD Snapping)";
                case "hud_scale_label" -> "HUD Widget Scale";
                case "global_shadow_label" -> "Global HUD Text Shadows";
                case "bg_dim_label" -> "Menu Background Dim";
                case "gui_anim_label" -> "Smooth Hover Animations";
                case "custom_rgb_label" -> "Custom Color (RGB Sliders):";
                case "active_badge" -> "✓ ACTIVE";
                case "activate_btn" -> "ACTIVATE";
                case "accounts_title" -> "PREMIUM ACCOUNTS";
                case "add_account_btn" -> "+ Add Account";
                case "active_account" -> "Active";
                case "enter_nickname" -> "Enter nickname...";
                case "login_microsoft" -> "🔑 Microsoft Login";
                case "open_browser" -> "Open Link";
                case "cancel" -> "Cancel";
                case "logged_in_as" -> "Logged in as ";
                default -> key;
            };
        }
    }
}
