package com.mooclient.util;

public class MooLanguage {

    public static final String PL = "pl";
    public static final String EN = "en";

    public static String current = PL;

    public static void toggleLanguage() {
        current = current.equals(PL) ? EN : PL;
        MooConfig.save();
    }

    public static String get(String key) {
        if (current.equals(PL)) {
            return switch (key) {
                case "singleplayer" -> "TRYB JEDNOOSOBOWY";
                case "multiplayer" -> "TRYB WIELOOSOBOWY";
                case "settings" -> "USTAWIENIA";
                case "quit" -> "WYJDŹ Z GRY";
                case "back" -> "← Powrót";
                case "on" -> "WŁ";
                case "off" -> "WYŁ";
                case "options" -> "OPCJE";
                case "enabled" -> "WŁĄCZONE";
                case "disabled" -> "WYŁĄCZONE";
                case "esc_hint" -> "Naciśnij ESC lub PRAWY SHIFT, aby zamknąć";
                case "mods_title" -> "MOO CLIENT • MODY";
                case "gamma_desc" -> "Maksymalna jasność w jaskiniach";
                case "fps_desc" -> "Licznik FPS w rogu ekranu";
                case "sprint_desc" -> "Automatyczny sprint";
                case "freelook_desc" -> "Swobodne obracanie kamery 360°";
                case "potions_desc" -> "Lista aktywnych mikstur na ekranie";
                case "nametags_desc" -> "Czytelne tagi graczy i ping";
                case "zoom_desc" -> "Płynne przybliżenie kamery (Zoom)";
                case "chat_desc" -> "Przezroczyste tło i nielimitowany czat";
                case "ping_desc" -> "Opóźnienie połączenia z serwerem";
                case "macro_desc" -> "Własne komendy pod klawiszami";
                case "waypoints_desc" -> "Punkty nawigacyjne i promień w świecie";
                case "cps_desc" -> "Licznik kliknięć na sekundę (CPS)";
                case "cps_opt_title" -> "CPS";
                case "cps_opt_subtitle" -> "Wyświetlaj i dostosuj swój licznik kliknięć na HUDzie.";
                case "cps_buttons_label" -> "Wyświetlane przyciski";
                case "fps_prefix_label" -> "Pokazuj przedrostek 'FPS:'";
                case "ping_prefix_label" -> "Pokazuj przedrostek 'Ping:'";
                case "cps_prefix_label" -> "Pokazuj przedrostek 'CPS:'";
                case "scoreboard_desc" -> "Dostosuj pozycję, tło, cienie i cyfry tablicy wyników";
                case "scoreboard_opt_title" -> "SCOREBOARD";
                case "scoreboard_opt_subtitle" ->
                    "Przesuwaj tablicę wyników, włącz cienie tekstu, ukrywaj tło i cyfry.";
                case "scoreboard_scores_label" -> "Wyświetlaj cyfry / punkty (Scores)";
                case "reset_pos_btn" -> "↺ Zresetuj pozycję";
                case "fps_opt_title" -> "FPS";
                case "fps_opt_subtitle" -> "Wyświetlaj i dostosuj swój licznik klatek na HUDzie.";
                case "ping_opt_title" -> "PING";
                case "ping_opt_subtitle" -> "Wyświetlaj i dostosuj opóźnienie połączenia na HUDzie.";
                case "waypoints_opt_title" -> "WAYPOINTS";
                case "waypoints_opt_subtitle" -> "Punkty nawigacyjne w świecie, odległości i promień świetlny.";
                case "waypoints_open_gui" -> "📍 Otwórz Menedżer Waypointów";
                case "show_distance_label" -> "Wyświetlaj odległość (metry)";
                case "show_beacons_label" -> "Promień światła w niebo (Beam)";
                case "show_labels_label" -> "Napisy nad punktami w świecie";
                case "sprint_opt_title" -> "TOGGLE SPRINT";
                case "sprint_opt_subtitle" -> "Dostosuj wskaźnik automatycznego sprintu na HUDzie.";
                case "freelook_opt_title" -> "FREELOOK";
                case "freelook_opt_subtitle" -> "Swobodny obrót kamery o 360° bez poruszania postacią.";
                case "potions_opt_title" -> "POTION EFFECTS";
                case "potions_opt_subtitle" -> "Wyświetlaj aktywne mikstury i czas ich trwania na HUDzie.";
                case "nametags_opt_title" -> "NAMETAGS";
                case "nametags_opt_subtitle" -> "Dostosuj tagi graczy i kolorowy ping.";
                case "zoom_opt_title" -> "ZOOM";
                case "zoom_opt_subtitle" -> "Dostosuj klawisz i poziom powiększenia kamery.";
                case "macro_opt_title" -> "MAKRA / AUTOTEXT";
                case "macro_opt_subtitle" -> "Wysyłaj komendy i wiadomości za pomocą skrótów klawiszowych.";
                case "chat_opt_title" -> "CHAT";
                case "chat_opt_subtitle" -> "Przezroczyste tło, nielimitowana historia i animacja czatu.";
                case "chat_transparent_label" -> "Przezroczyste tło czatu";
                case "chat_unlimited_label" -> "Nielimitowana historia czatu";
                case "chat_smooth_label" -> "Płynna animacja czatu";
                case "style_label" -> "Styl wyświetlania";
                case "bg_label" -> "Ciemne tło pod napisem";
                case "shadow_label" -> "Cień tekstu";
                case "prefix_label" -> "Pokazuj przedrostek 'FPS:'";
                case "compact_label" -> "Tryb kompaktowy";
                case "show_ping_label" -> "Wyświetlaj ping";
                case "show_self_ping_label" -> "Pokaż ping nad sobą (Self Ping)";
                case "ping_pos_label" -> "Pozycja pingu";
                case "ping_pos_beside" -> "Obok nicku";
                case "ping_pos_above" -> "Nad nickiem";
                case "show_logo_label" -> "Logo Moo Client przy nicku";
                case "remove_bg_label" -> "Usuń tło z nametaga";
                case "waypoint_scale_label" -> "Skala / Rozmiar waypointów";
                case "death_waypoint_label" -> "Automatyczny punkt śmierci (Death Point)";
                case "wp_all_dimensions" -> "Wszystkie wymiary";
                case "wp_all_servers" -> "Wszystkie serwery";
                case "wp_custom_color" -> "Własny kolor";
                case "factor_label" -> "Współczynnik powiększenia";
                case "smooth_zoom_label" -> "Płynne przybliżanie";
                case "gamma_opt_title" -> "GAMMA";
                case "gamma_opt_subtitle" -> "Rozjaśnij ciemne jaskinie i noc.";
                case "fullbright_label" -> "Widzenie w ciemności (Fullbright)";
                case "mode_label" -> "Tryb działania";
                case "invert_pitch_label" -> "Odwróć oś Y (Invert Pitch)";
                case "client_settings_title" -> "MOO CLIENT • USTAWIENIA";
                case "tab_accent" -> "🎨 KOLOR AKCENTU";
                case "tab_hud" -> "📍 HUD & WIDGETY";
                case "tab_gui" -> "✨ WYGLĄD GUI";
                case "tab_profiles" -> "📁 PROFILE";
                case "reset_hud_btn" -> "↺ PRZYWRÓĆ POZYCJE HUD";
                case "reset_hud_done" -> "✓ Pozycje HUD zresetowane!";
                case "hud_snapping_label" -> "Przyciąganie do krawędzi (HUD Snapping)";
                case "hud_scale_label" -> "Skala widgetów HUD (HUD Scale)";
                case "global_shadow_label" -> "Globalne cienie tekstu HUD (Text Shadows)";
                case "bg_dim_label" -> "Przyciemnienie tła menu (Background Dim)";
                case "gui_anim_label" -> "Płynne animacje podświetleń (GUI Animations)";
                case "custom_rgb_label" -> "Dostosuj własny kolor (RGB Sliders):";
                case "active_badge" -> "✓ AKTYWNY";
                case "activate_btn" -> "AKTYWUJ";
                case "accounts_title" -> "KONTA PREMIUM";
                case "add_account_btn" -> "+ Dodaj konto";
                case "active_account" -> "Aktywne";
                case "enter_nickname" -> "Wpisz nick...";
                case "login_microsoft" -> "🔑 Logowanie Microsoft";
                case "open_browser" -> "Otwórz link";
                case "cancel" -> "Anuluj";
                case "logged_in_as" -> "Zalogowano jako ";
                default -> key;
            };
        } else {
            return switch (key) {
                case "singleplayer" -> "SINGLEPLAYER";
                case "multiplayer" -> "MULTIPLAYER";
                case "settings" -> "SETTINGS";
                case "quit" -> "QUIT GAME";
                case "back" -> "← Back";
                case "on" -> "ON";
                case "off" -> "OFF";
                case "options" -> "OPTIONS";
                case "enabled" -> "ENABLED";
                case "disabled" -> "DISABLED";
                case "esc_hint" -> "Press ESC or RIGHT SHIFT to close";
                case "mods_title" -> "MOO CLIENT • MODS";
                case "gamma_desc" -> "Max brightness for dark caves";
                case "fps_desc" -> "FPS Counter on HUD";
                case "sprint_desc" -> "Automatic Toggle Sprint";
                case "freelook_desc" -> "360° Free Camera View";
                case "potions_desc" -> "Active Potions & Timers";
                case "nametags_desc" -> "Nametag Badges & Ping";
                case "zoom_desc" -> "Smooth Camera Zoom";
                case "chat_desc" -> "Transparent Chat & History";
                case "ping_desc" -> "Ping Latency on HUD";
                case "macro_desc" -> "Macro Command Keybinds";
                case "waypoints_desc" -> "In-world waypoints and beacon beams";
                case "cps_desc" -> "Clicks Per Second (CPS) on HUD";
                case "cps_opt_title" -> "CPS";
                case "cps_opt_subtitle" -> "Display and customize your CPS counter on the HUD.";
                case "cps_buttons_label" -> "Displayed Buttons";
                case "fps_prefix_label" -> "Show 'FPS:' Prefix";
                case "ping_prefix_label" -> "Show 'Ping:' Prefix";
                case "cps_prefix_label" -> "Show 'CPS:' Prefix";
                case "scoreboard_desc" -> "Customize scoreboard position, background, shadows and scores";
                case "scoreboard_opt_title" -> "SCOREBOARD";
                case "scoreboard_opt_subtitle" -> "Reposition scoreboard, toggle text shadow, background and scores.";
                case "scoreboard_scores_label" -> "Show Scores / Numbers";
                case "fps_opt_title" -> "FPS";
                case "fps_opt_subtitle" -> "Display and customize your FPS on the HUD.";
                case "ping_opt_title" -> "PING";
                case "ping_opt_subtitle" -> "Display and customize your real-time latency on the HUD.";
                case "waypoints_opt_title" -> "WAYPOINTS";
                case "waypoints_opt_subtitle" -> "In-world navigation points, distances and beacon beams.";
                case "waypoints_open_gui" -> "📍 Open Waypoints Manager";
                case "show_distance_label" -> "Show Distance (Meters)";
                case "show_beacons_label" -> "Show Sky Beacon Beams";
                case "show_labels_label" -> "Show In-World Name Labels";
                case "sprint_opt_title" -> "SPRINT";
                case "sprint_opt_subtitle" -> "Customize your Toggle Sprint indicator on HUD.";
                case "freelook_opt_title" -> "FREELOOK";
                case "freelook_opt_subtitle" -> "Free 360° camera rotation without moving character.";
                case "potions_opt_title" -> "POTION EFFECTS";
                case "potions_opt_subtitle" -> "Display active potions and countdown timer on HUD.";
                case "nametags_opt_title" -> "NAMETAGS";
                case "nametags_opt_subtitle" -> "Customize player nametags and colored ping latency.";
                case "zoom_opt_title" -> "ZOOM";
                case "zoom_opt_subtitle" -> "Customize zoom keybind and magnification factor.";
                case "macro_opt_title" -> "MACRO / AUTOTEXT";
                case "macro_opt_subtitle" -> "Execute commands & messages using custom keybinds.";
                case "chat_opt_title" -> "CHAT";
                case "chat_opt_subtitle" -> "Transparent background, unlimited history & smooth slide animation";
                case "chat_transparent_label" -> "Transparent Background";
                case "chat_unlimited_label" -> "Unlimited Chat History";
                case "chat_smooth_label" -> "Smooth Chat Animation";
                case "style_label" -> "Appearance Style";
                case "bg_label" -> "Show Background";
                case "shadow_label" -> "Text Shadow";
                case "prefix_label" -> "Show 'FPS:' Prefix";
                case "compact_label" -> "Compact Mode";
                case "show_ping_label" -> "Show Ping";
                case "show_self_ping_label" -> "Show Self Ping";
                case "ping_pos_label" -> "Ping Position";
                case "ping_pos_beside" -> "Beside Name";
                case "ping_pos_above" -> "Above Name";
                case "show_logo_label" -> "Client Logo Badge";
                case "remove_bg_label" -> "Remove Nametag Background";
                case "waypoint_scale_label" -> "Waypoint Scale / Size";
                case "death_waypoint_label" -> "Auto Death Waypoint";
                case "wp_all_dimensions" -> "All Dimensions";
                case "wp_all_servers" -> "All Servers";
                case "wp_custom_color" -> "Custom Color";
                case "factor_label" -> "Zoom Factor";
                case "smooth_zoom_label" -> "Smooth Zoom";
                case "gamma_opt_title" -> "GAMMA";
                case "gamma_opt_subtitle" -> "See clearly in dark caves and night";
                case "fullbright_label" -> "Fullbright Vision";
                case "mode_label" -> "Activation Mode";
                case "invert_pitch_label" -> "Invert Y-Axis";
                case "client_settings_title" -> "MOO CLIENT • SETTINGS";
                case "tab_accent" -> "🎨 ACCENT COLOR";
                case "tab_hud" -> "📍 HUD & WIDGETS";
                case "tab_gui" -> "✨ GUI THEME";
                case "tab_profiles" -> "📁 PROFILES";
                case "reset_hud_btn" -> "↺ RESET HUD POSITIONS";
                case "reset_hud_done" -> "✓ HUD Positions Reset!";
                case "hud_snapping_label" -> "Edge Snapping (HUD Snapping)";
                case "hud_scale_label" -> "HUD Widget Scale";
                case "global_shadow_label" -> "Global HUD Text Shadows";
                case "bg_dim_label" -> "Menu Background Dim";
                case "gui_anim_label" -> "Smooth Hover Animations";
                case "custom_rgb_label" -> "Custom Color (RGB Sliders):";
                case "active_badge" -> "✓ ACTIVE";
                case "activate_btn" -> "ACTIVATE";
                case "accounts_title" -> "PREMIUM ACCOUNTS";
                case "add_account_btn" -> "+ Add Account";
                case "active_account" -> "Active";
                case "enter_nickname" -> "Enter nickname...";
                case "login_microsoft" -> "🔑 Microsoft Login";
                case "open_browser" -> "Open Link";
                case "cancel" -> "Cancel";
                case "logged_in_as" -> "Logged in as ";
                default -> key;
            };
        }
    }
}
